package cashtech.jar;

import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.nio.file.StandardOpenOption;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.time.format.FormatStyle;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import models.Usuario;
import services.MaquinaService;
import services.GerarLog;
import services.KillProcessosService;
import services.LoginService;
import services.MonitorarService;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author PC
 */
public class LoginSwing extends javax.swing.JFrame {

    /**
     * Creates new form LoginSwing
     */
    public LoginSwing() {
        initComponents();
    }

    KillProcessosService killProcessosService = new KillProcessosService();
    MaquinaService maquinaService = new MaquinaService();
    LoginService loginService = new LoginService();
    MonitorarService monitorarService = new MonitorarService();

    GerarLog gerarLog = new GerarLog();

    Color verde = new Color(0, 128, 0);
    Color vermelho = new Color(128, 0, 0);
    Color preto = new Color(0, 0, 0);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelBranco = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblBemVindo = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtSenha = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        verificaLogin = new javax.swing.JLabel();
        PanelAzul = new javax.swing.JPanel();
        lblBemVindo2 = new javax.swing.JLabel();
        lblSolucao = new javax.swing.JLabel();
        lblGraficos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        PanelBranco.setBackground(new java.awt.Color(255, 255, 255));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logo-cashtech.png"))); // NOI18N

        lblBemVindo.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblBemVindo.setForeground(new java.awt.Color(63, 63, 63));
        lblBemVindo.setText("Olá, Bem-vindo(a)!");

        lblUsuario.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(127, 125, 125));
        lblUsuario.setText("Usuário");

        lblSenha.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblSenha.setForeground(new java.awt.Color(127, 125, 125));
        lblSenha.setText("Senha");

        txtUsuario.setBackground(new java.awt.Color(248, 248, 248));

        txtSenha.setBackground(new java.awt.Color(248, 248, 248));

        btnLogin.setBackground(new java.awt.Color(0, 56, 73));
        btnLogin.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        verificaLogin.setBackground(new java.awt.Color(255, 0, 51));
        verificaLogin.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout PanelBrancoLayout = new javax.swing.GroupLayout(PanelBranco);
        PanelBranco.setLayout(PanelBrancoLayout);
        PanelBrancoLayout.setHorizontalGroup(
            PanelBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBrancoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogin)
                .addGap(234, 234, 234))
            .addGroup(PanelBrancoLayout.createSequentialGroup()
                .addGroup(PanelBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelBrancoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(verificaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelBrancoLayout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(PanelBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSenha)
                                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(PanelBrancoLayout.createSequentialGroup()
                                    .addGap(3, 3, 3)
                                    .addComponent(lblUsuario)
                                    .addGap(112, 112, 112)))
                            .addGroup(PanelBrancoLayout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(lblBemVindo))
                            .addGroup(PanelBrancoLayout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addComponent(lblLogo)))))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        PanelBrancoLayout.setVerticalGroup(
            PanelBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBrancoLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(lblLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBemVindo)
                .addGap(18, 18, 18)
                .addComponent(lblUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(verificaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLogin)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        PanelAzul.setBackground(new java.awt.Color(38, 50, 56));

        lblBemVindo2.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblBemVindo2.setForeground(new java.awt.Color(255, 255, 255));
        lblBemVindo2.setText("Seja bem-vindo a CashTech!");

        lblSolucao.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblSolucao.setForeground(new java.awt.Color(100, 199, 175));
        lblSolucao.setText("Trazendo solução ao seu negócio.");

        lblGraficos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/cadastro-Graphic.png"))); // NOI18N

        javax.swing.GroupLayout PanelAzulLayout = new javax.swing.GroupLayout(PanelAzul);
        PanelAzul.setLayout(PanelAzulLayout);
        PanelAzulLayout.setHorizontalGroup(
            PanelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAzulLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(PanelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblGraficos)
                    .addGroup(PanelAzulLayout.createSequentialGroup()
                        .addComponent(lblSolucao)
                        .addGap(45, 45, 45)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAzulLayout.createSequentialGroup()
                .addGap(0, 67, Short.MAX_VALUE)
                .addComponent(lblBemVindo2, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        PanelAzulLayout.setVerticalGroup(
            PanelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAzulLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(lblBemVindo2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSolucao)
                .addGap(18, 18, 18)
                .addComponent(lblGraficos)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(164, Short.MAX_VALUE)
                .addComponent(PanelBranco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelAzul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelBranco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelAzul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Pecisar usar o IoException pra caso dê problema não criação do arquivo
    //ou erro durante a leitura ou gravação de dados
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {
        String usuario = txtUsuario.getText();
        String senha = txtSenha.getText();

        List<Usuario> usuariosRetornado = loginService.verificarLogin(usuario, senha);

        //Importar a classe File para poder criar um arquivo
        if (usuario.isEmpty() || senha.isEmpty()) {
            verificaLogin.setForeground(preto);
            verificaLogin.setText("Complete todos os campos!");
        } else if (usuariosRetornado.size() == 0) {
            verificaLogin.setForeground(vermelho);
            verificaLogin.setText("Usuário não encontrado!");
        } else {

            gerarLog.login(usuario);

            Usuario usuarioVerificado = usuariosRetornado.get(0);
            System.out.println("Usuario: " + usuarioVerificado.getNome());
            Integer idEmpresaUsuario = usuarioVerificado.getEmpresa_id();

            verificaLogin.setForeground(verde);
            verificaLogin.setText("Login efetuado com sucesso!");

            Integer idEmpresa = usuarioVerificado.getEmpresa_id();
            if (!loginService.hasMaquina()) {
//                 Cadastrar Máquina
                maquinaService.executarCadastro(idEmpresa);
            }

//             Identificar máquina e começar a monitorar o processo
            Integer idAtm = maquinaService.identificarMaquina();

            killProcessosService.monitorar(idAtm, idEmpresa);
            monitorarService.monitorarHardware(idAtm, idEmpresaUsuario);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginSwing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelAzul;
    private javax.swing.JPanel PanelBranco;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel lblBemVindo;
    private javax.swing.JLabel lblBemVindo2;
    private javax.swing.JLabel lblGraficos;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblSolucao;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTextField txtSenha;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JLabel verificaLogin;
    // End of variables declaration//GEN-END:variables
}